<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://localhost:8080/RestaurantSOAWP/AccessServer.jws" 
xmlns:intf="http://localhost:8080/RestaurantSOAWP/AccessServer.jws" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
 xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost:8080/RestaurantSOAWP/AccessServer.jws">

 <wsdl:part name="nomRecette" type="xsd:string"/>
 <wsdl:part name="descriptionRecette" type="xsd:string"/>
 <wsdl:message name="idRecette">


<wsdl:portType name="Recette">
<wsdl:operation name="recette" parameterOrder="nomRecette","descriptionRecette","idRecette">
<wsdl:input message="impl:" name=""/>
<wsdl:output message="impl:" name=""/>
</wsdl:operation>
</wsdl:portType>